export default [  
  {
    patRegNo: "L1PA0001",
    name: "Ahmad Hussein Habib",
    gender: "M",
    phone: "08119671607",
    address: "Samaru ABU Zaria",
    profilePix: '/static/images/avatars/avatar_3.png',
    genotype: "AA",
    bloodGroup: "O+",
    knownAllegies: "None",
    createdAt: 1555016400000,
  },
  {
    patRegNo: "L2PA0002",
    name: "Aisha Oluwabukola",
    gender: "F",
    phone: "08119671607",
    address: "Samaru ABU Zaria",
    profilePix: '/static/images/avatars/avatar_1.png',
    genotype: "AA",
    bloodGroup: "O+",
    knownAllegies: "None",
    createdAt: 1555016400000,
  },
  {
    patRegNo: "L3PA0002",
    name: "Nafisat Adamu",
    gender: "F",
    phone: "08119671607",
    address: "Samaru ABU Zaria",
    profilePix: '/static/images/avatars/avatar_2.png',
    genotype: "AA",
    bloodGroup: "O+",
    knownAllegies: "None",
    createdAt: 1555016400000,
  },
  {
    patRegNo: "L1PA0001",
    name: "Ahmad Hussein Habib",
    gender: "M",
    phone: "08119671607",
    address: "Samaru ABU Zaria",
    profilePix: '/static/images/avatars/avatar_5.png',
    genotype: "AA",
    bloodGroup: "O+",
    knownAllegies: "None",
    createdAt: 1555016400000,
  },
  {
    patRegNo: "L3PA0002",
    name: "Nafisat Adamu",
    gender: "F",
    phone: "08119671607",
    address: "Samaru ABU Zaria",
    profilePix: '/static/images/avatars/avatar_4.png',
    genotype: "AA",
    bloodGroup: "O+",
    knownAllegies: "None",
    createdAt: 1555016400000,
  },
  
];
